FROM public.ecr.aws/supabase/postgres@sha256:06ddc7962e11ab0f4f0334fd05671e97c30ea202f6e6a7113800bd3d6e416108
COPY supabase-prod-ca-2021.crt /etc/f15/supabase-prod-ca-2021.crt
ENV PGSSLMODE=verify-full PGSSLROOTCERT=/etc/f15/supabase-prod-ca-2021.crt PGCONNECT_TIMEOUT=10
ENV PGOPTIONS="-c default_transaction_read_only=on -c statement_timeout=120000"
