"""Purchase Intelligence policy boundaries.

The purchase domain owns strategy policy and product-quality vocabulary.  The
existing recommendation domain remains the persistence and implementation home
for the active Style strategy during V3-05.0.
"""

from app.domains.purchase.contract import (
    CARE_PURCHASE_ASSESSMENT_SCHEMA_VERSION,
    CARE_PURCHASE_ASSESSMENT_VERSION,
    CARE_PURCHASE_CANDIDATE_SCHEMA_VERSION,
    CARE_PURCHASE_CATEGORIES,
    CARE_PURCHASE_EVIDENCE_SCHEMA_VERSION,
    CARE_PURCHASE_EVIDENCE_VERSION,
    CARE_PURCHASE_VALUE_SCHEMA_VERSION,
    CARE_PURCHASE_VALUE_VERSION,
    CARE_PURCHASE_VERDICT_SCHEMA_VERSION,
    CARE_PURCHASE_VERDICT_VERSION,
    FRAGRANCE_PURCHASE_CATEGORIES,
    PRODUCT_QUALITY_CONTRACT_VERSION,
    PRODUCT_QUALITY_DIMENSIONS,
    PURCHASE_CANDIDATE_TRUTH_VERSION,
    PURCHASE_CATEGORY_LABELS,
    PURCHASE_INTELLIGENCE_FOUNDATION_VERSION,
    PURCHASE_PROHIBITED_CATEGORIES,
    PURCHASE_STRATEGY_REGISTRY_VERSION,
    STYLE_PURCHASE_CATEGORIES,
    PurchaseStrategy,
    PurchaseStrategyBoundaryError,
    resolve_purchase_strategy,
)

__all__ = [
    "CARE_PURCHASE_ASSESSMENT_SCHEMA_VERSION",
    "CARE_PURCHASE_ASSESSMENT_VERSION",
    "CARE_PURCHASE_EVIDENCE_SCHEMA_VERSION",
    "CARE_PURCHASE_EVIDENCE_VERSION",
    "CARE_PURCHASE_VALUE_SCHEMA_VERSION",
    "CARE_PURCHASE_VALUE_VERSION",
    "CARE_PURCHASE_VERDICT_SCHEMA_VERSION",
    "CARE_PURCHASE_VERDICT_VERSION",
    "CARE_PURCHASE_CATEGORIES",
    "CARE_PURCHASE_CANDIDATE_SCHEMA_VERSION",
    "FRAGRANCE_PURCHASE_CATEGORIES",
    "PRODUCT_QUALITY_CONTRACT_VERSION",
    "PRODUCT_QUALITY_DIMENSIONS",
    "PURCHASE_CATEGORY_LABELS",
    "PURCHASE_INTELLIGENCE_FOUNDATION_VERSION",
    "PURCHASE_CANDIDATE_TRUTH_VERSION",
    "PURCHASE_PROHIBITED_CATEGORIES",
    "PURCHASE_STRATEGY_REGISTRY_VERSION",
    "STYLE_PURCHASE_CATEGORIES",
    "PurchaseStrategy",
    "PurchaseStrategyBoundaryError",
    "resolve_purchase_strategy",
]
