"""Strict API contracts for structured supplement label facts."""
from __future__ import annotations

import uuid
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.domains.supplements import strings as copy

#: Retry keys under this prefix belong to the photo bridge and are written by
#: the server only. A manual entry may not borrow one, so a manual row can never
#: be returned as if it were a photo transcription.
RESERVED_MUTATION_PREFIX = "photo:"


class LabelComponentCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    raw_name: str = Field(min_length=1, max_length=160)
    amount: Decimal | None = Field(default=None, ge=0, max_digits=20, decimal_places=6)
    unit: str | None = Field(default=None, max_length=32)
    serving_text: str | None = Field(default=None, max_length=160)
    client_mutation_id: str | None = Field(default=None, max_length=80)

    @field_validator("client_mutation_id")
    @classmethod
    def _not_reserved(cls, value: str | None) -> str | None:
        if value is not None and value.startswith(RESERVED_MUTATION_PREFIX):
            raise ValueError(copy.text("supplement.label_fact.reserved_key"))
        return value


class LabelComponentPatch(BaseModel):
    model_config = ConfigDict(extra="forbid")

    raw_name: str | None = Field(default=None, min_length=1, max_length=160)
    amount: Decimal | None = Field(default=None, ge=0, max_digits=20, decimal_places=6)
    unit: str | None = Field(default=None, max_length=32)
    serving_text: str | None = Field(default=None, max_length=160)


class LabelComponentConfirm(BaseModel):
    model_config = ConfigDict(extra="forbid")

    confirmed: bool = True


class LabelPhotoTranscribe(BaseModel):
    """Read one owned photo onto one owned supplement, as drafts."""

    model_config = ConfigDict(extra="forbid")

    media_asset_id: uuid.UUID
    #: Generated by the app once per photo; a retry sends the same value.
    client_request_id: str = Field(min_length=8, max_length=64, pattern=r"^[A-Za-z0-9_-]+$")
