"""Static salon ideas and quiz questions (browse-only, no booking)."""

SALON_IDEAS = [
    {
        "id": "1",
        "name": "Hair Spa",
        "category": "Hair",
        "for_goal": "Healthier-looking hair length and shine",
        "description": "Deep conditioning with steam — useful when hair looks dry or rough at the ends.",
        "how_often_idea": "Every 4–6 weeks",
        "suitable_for": ["dry", "damaged", "frizz"],
    },
    {
        "id": "2",
        "name": "Cleanup / Basic Facial",
        "category": "Skin",
        "for_goal": "Fresher-looking face skin",
        "description": "Gentle cleanse and glow pack — a salon idea when skin looks dull or congested.",
        "how_often_idea": "Every 3–4 weeks",
        "suitable_for": ["all skin types"],
    },
    {
        "id": "3",
        "name": "Head Oil Massage (Champi)",
        "category": "Hair",
        "for_goal": "Relaxed scalp and cared-for hair roots",
        "description": "Warm oil massage for scalp comfort — popular across India.",
        "how_often_idea": "Weekly or bi-weekly",
        "suitable_for": ["all hair types"],
    },
    {
        "id": "4",
        "name": "Manicure",
        "category": "Hands & Nails",
        "for_goal": "Healthier-looking hand skin and nails",
        "description": "Nail care, cuticle tidy, and hand moisturise — not a medical treatment.",
        "how_often_idea": "Every 2–3 weeks",
        "suitable_for": ["all"],
    },
    {
        "id": "5",
        "name": "Pedicure",
        "category": "Hands & Nails",
        "for_goal": "Softer-looking feet and neat nails",
        "description": "Foot scrub and nail care for everyday comfort and grooming.",
        "how_often_idea": "Every 3–4 weeks",
        "suitable_for": ["all"],
    },
    {
        "id": "6",
        "name": "Fruit / Vitamin Facial",
        "category": "Skin",
        "for_goal": "Brighter-looking face skin",
        "description": "Gentle vitamin-forward facial idea when skin looks tired or dull.",
        "how_often_idea": "Monthly",
        "suitable_for": ["dull", "normal", "combination"],
    },
    {
        "id": "7",
        "name": "Anti-Tan Facial (salon idea)",
        "category": "Skin",
        "for_goal": "More even-looking tone after sun exposure",
        "description": "Salon idea if face looks tanned or uneven from sun — lifestyle care, not diagnosis.",
        "how_often_idea": "As needed after heavy sun",
        "suitable_for": ["sun-exposed"],
    },
    {
        "id": "8",
        "name": "Keratin / Smoothening consult",
        "category": "Hair",
        "for_goal": "Easier everyday hair manageability",
        "description": "Ask a stylist only if frizz or manageability is a daily struggle — discuss aftercare first.",
        "how_often_idea": "Discuss with stylist (months apart)",
        "suitable_for": ["wavy", "curly", "frizz"],
    },
    {
        "id": "9",
        "name": "Threading / Grooming",
        "category": "Grooming",
        "for_goal": "Neat brow and face framing",
        "description": "Simple grooming visit for a polished everyday look.",
        "how_often_idea": "Every 2–3 weeks",
        "suitable_for": ["all"],
    },
    {
        "id": "10",
        "name": "Blow-dry & Style",
        "category": "Hair",
        "for_goal": "Occasion-ready hair shape",
        "description": "Styling visit for office, festive, or wedding-guest days — pair with your colour palette.",
        "how_often_idea": "For occasions",
        "suitable_for": ["all hair types"],
    },
]

QUIZ_QUESTIONS = [
    {
        "id": "q1",
        "question": "What bothers you most about your hair right now?",
        "options": ["Frizz & dryness", "Thin-looking / low volume", "Breakage & damage", "Oily roots", "No major concern"],
    },
    {
        "id": "q2",
        "question": "How does your face skin usually feel?",
        "options": ["Oily with shine", "Dry or tight", "Combination", "Balanced", "Easily uncomfortable"],
    },
    {
        "id": "q3",
        "question": "What would you like your skin to look more like?",
        "options": ["Fewer pimples", "More even tone", "Less dullness", "Better hydration", "Smoother texture"],
    },
    {
        "id": "q4",
        "question": "Your diet style?",
        "options": ["Vegetarian", "Eggetarian", "Non-vegetarian", "Prefer not to say"],
    },
    {
        "id": "q5",
        "question": "Your everyday style vibe?",
        "options": ["Natural & easy", "Polished & neat", "Festive & bold", "Classic Indian wear", "Trend-led / experimental"],
    },
    {
        "id": "q6",
        "question": "How would you describe your body frame (for clothing fit ideas)?",
        "options": ["Slim / petite", "Average", "Athletic", "Curvy", "Plus / fuller", "Prefer not to say"],
    },
]
