"""Synthetic late-review regressions; never production recovery evidence."""
from __future__ import annotations

import hashlib
import importlib.util
import json
import os
from copy import deepcopy
from pathlib import Path

import pytest
from app import config
from app.domains.off import importer, local_recovery, store
from app.operations import recovery
from sqlalchemy import text
from sqlalchemy.engine import make_url

ROOT = Path(__file__).resolve().parents[2]


@pytest.mark.parametrize("problem", ["duplicate", "key", "source_size", "source_digest", "missing", "extra", "recovered_digest"])
def test_object_proofs_are_exactly_bound_to_independent_source(problem):
    key = hashlib.sha256(b"synthetic/object").hexdigest()
    digest = hashlib.sha256(b"synthetic bytes").hexdigest()
    source = {"storage_objects": 1, "storage_byte_manifest": [{"key_sha256": key, "bytes": 15, "sha256": digest}]}
    proof = recovery.ByteRecovery(15, digest, key, 15, digest)
    recovery.assert_storage_proofs(source, [proof])
    values = dict(bytes=15, sha256=digest, source_key_sha256=key, source_bytes=15, source_sha256=digest)
    if problem == "key":
        values["source_key_sha256"] = "a" * 64
    elif problem == "source_size":
        values["source_bytes"] = 16
    elif problem == "source_digest":
        values["source_sha256"] = "a" * 64
    elif problem == "recovered_digest":
        values["sha256"] = "a" * 64
    proofs = [recovery.ByteRecovery(**values)]
    if problem in {"duplicate", "extra"}:
        proofs.append(proof)
    elif problem == "missing":
        proofs = []
    with pytest.raises(recovery.RecoveryFailed):
        recovery.assert_storage_proofs(source, proofs)


def test_zero_source_refuses_extra_fake_storage_proof():
    with pytest.raises(recovery.RecoveryFailed):
        recovery.assert_storage_proofs({"storage_objects": 0}, [recovery.ByteRecovery(1, "a" * 64, "b" * 64, 1, "a" * 64)])


@pytest.fixture
def parity_database():
    url = make_url(os.environ["POSTGRES_URL"]).set(drivername="postgresql", database="f15_manifest_test")
    admin = url.set(database="postgres")
    env = dict(os.environ, PGPASSWORD=url.password or "")
    def sql(query, *, database=url):
        return recovery.run_checked(["psql", "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-v", "SHOW_CONTEXT=never",
                                     "--dbname", database.set(password=None).render_as_string(hide_password=False), "-c", query], environment=env)
    exists = sql("SELECT EXISTS(SELECT FROM pg_database WHERE datname='f15_manifest_test')", database=admin).strip()
    if exists == "f":
        sql('CREATE DATABASE f15_manifest_test', database=admin)
    sql("""DROP SCHEMA public CASCADE; CREATE SCHEMA public;
        CREATE SCHEMA IF NOT EXISTS extensions; CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
        CREATE SCHEMA IF NOT EXISTS auth; CREATE TABLE IF NOT EXISTS auth.users(id int);
        CREATE SCHEMA IF NOT EXISTS storage; CREATE TABLE IF NOT EXISTS storage.objects(id int);
        CREATE TABLE IF NOT EXISTS storage.buckets(id int);
        CREATE SCHEMA IF NOT EXISTS vault; CREATE TABLE IF NOT EXISTS vault.secrets(id int);
        CREATE TABLE public.alembic_version(version_num text); INSERT INTO public.alembic_version VALUES('d0e1f2g3h4');
        CREATE TABLE public.accounts(id text); CREATE TABLE public.external_integrations(id text);
        CREATE TABLE public.inventory_items(id text); CREATE TABLE public.invites(id text);
        CREATE TABLE public.media_assets(id text); CREATE TABLE public.product_records(id text);
        CREATE TABLE public.scan_devices(id text); CREATE TABLE public.scans(id text);
        CREATE TABLE public.outside_eight(id integer GENERATED BY DEFAULT AS IDENTITY,
          value text NOT NULL DEFAULT 'fixture', j json, jb jsonb, n numeric, b bool, optional text,
          t timestamptz, d date, computed integer GENERATED ALWAYS AS (id+1) STORED);
        INSERT INTO public.outside_eight(value,j,jb,n,b,optional,t,d) VALUES
          ('private synthetic only','{ "a":1 }','{"a":1}',42.50,true,NULL,'2020-01-02 03:04:05+00','2020-01-02');
    """)
    query = (ROOT / "scripts/f15/safe-source-manifest.sql").read_text(encoding="utf-8")
    def manifest(change=""):
        # The mutation commits only to this named synthetic fixture database.
        if change:
            sql(change)
        return json.loads(sql(query))
    yield manifest
    sql("DROP SCHEMA public CASCADE; CREATE SCHEMA public")


@pytest.mark.parametrize("change", [
    "UPDATE outside_eight SET value='different'",
    "UPDATE outside_eight SET j='{\"a\":2}'",
    "UPDATE outside_eight SET jb='{\"a\":2}'",
    "UPDATE outside_eight SET n=42.51",
    "UPDATE outside_eight SET b=false",
    "UPDATE outside_eight SET optional=''",
    "UPDATE outside_eight SET t=t+interval '1 second'",
    "UPDATE outside_eight SET d=d+1",
])
def test_complete_non_id_row_mutants_detected(parity_database, change):
    before = parity_database()
    after = parity_database(change)
    assert before["public_table_counts"] == after["public_table_counts"]
    assert before["sorted_primary_id_sha256"] == after["sorted_primary_id_sha256"]
    assert before["public_table_content_sha256"]["outside_eight"] != after["public_table_content_sha256"]["outside_eight"]
    with pytest.raises(recovery.RecoveryFailed, match="MANIFEST_MISMATCH"):
        recovery.assert_manifest_parity(before, after)


@pytest.mark.parametrize("change", [
    "ALTER TABLE outside_eight ALTER COLUMN value DROP NOT NULL",
    "ALTER TABLE outside_eight ALTER COLUMN value SET DEFAULT 'changed'",
    "ALTER TABLE outside_eight ALTER COLUMN value TYPE varchar(100)",
    "ALTER TABLE outside_eight DROP COLUMN computed; ALTER TABLE outside_eight ADD COLUMN computed int GENERATED ALWAYS AS(id+2) STORED",
    "ALTER TABLE outside_eight ALTER COLUMN id SET GENERATED ALWAYS",
])
def test_complete_column_authority_mutants_detected(parity_database, change):
    before = parity_database()
    after = parity_database(change)
    assert before["public_columns"] != after["public_columns"]
    with pytest.raises(recovery.RecoveryFailed, match="MANIFEST_MISMATCH"):
        recovery.assert_manifest_parity(before, after)


def test_unsupported_type_fails_even_on_empty_table(parity_database):
    with pytest.raises(recovery.RecoveryFailed):
        parity_database("CREATE TABLE unsupported(value xml)")


def test_logical_column_order_survives_dropped_slots_and_rejects_reordering(parity_database):
    before = parity_database("""CREATE TABLE ordinal_gap(first integer, discarded text, last text);
        ALTER TABLE ordinal_gap DROP COLUMN discarded;
        INSERT INTO ordinal_gap(first,last) VALUES (7,'synthetic');""")
    # Replay the visible schema exactly as a logical dump does, without the
    # source's invisible dropped-column slot.
    compacted = parity_database("""DROP TABLE ordinal_gap;
        CREATE TABLE ordinal_gap(first integer, last text);
        INSERT INTO ordinal_gap(first,last) VALUES (7,'synthetic');""")
    assert [c["attnum"] for c in before["public_columns"] if c["table"] == "ordinal_gap"] == [1, 2]
    assert before["public_columns"] == compacted["public_columns"]
    recovery.assert_manifest_parity(before, compacted)
    reordered = parity_database("""DROP TABLE ordinal_gap;
        CREATE TABLE ordinal_gap(last text, first integer);
        INSERT INTO ordinal_gap(first,last) VALUES (7,'synthetic');""")
    assert before["public_columns"] != reordered["public_columns"]
    with pytest.raises(recovery.RecoveryFailed, match="MANIFEST_MISMATCH"):
        recovery.assert_manifest_parity(before, reordered)


def test_row_multiset_preserves_duplicates_and_ignores_order(parity_database):
    before = parity_database("CREATE TABLE duplicate_probe(v text); INSERT INTO duplicate_probe VALUES ('a'),('b'),('a')")
    reordered = parity_database("TRUNCATE duplicate_probe; INSERT INTO duplicate_probe VALUES ('a'),('a'),('b')")
    assert before["public_table_content_sha256"] == reordered["public_table_content_sha256"]
    changed = parity_database("TRUNCATE duplicate_probe; INSERT INTO duplicate_probe VALUES ('b'),('a'),('b')")
    assert before["public_table_content_sha256"] != changed["public_table_content_sha256"]


def test_generated_expression_same_ordinal_is_detected(parity_database):
    before=parity_database()
    if before["server_version"].split('.')[0] != '17':
        pytest.skip('PG17 SET EXPRESSION regression; PG16 drop/recreate covered separately')
    after=parity_database("ALTER TABLE outside_eight ALTER COLUMN computed SET EXPRESSION AS (id+2)")
    source=next(c for c in before['public_columns'] if c['column']=='computed')
    target=next(c for c in after['public_columns'] if c['column']=='computed')
    assert source['attnum'] == target['attnum']
    assert source['default_expression_sha256'] != target['default_expression_sha256']


def test_array_lower_bounds_are_part_of_complete_content(parity_database):
    before=parity_database("CREATE TABLE array_probe(v int[]); INSERT INTO array_probe VALUES ('[0:1]={1,2}')")
    after=parity_database("UPDATE array_probe SET v=ARRAY[1,2]")
    assert before['public_table_counts']==after['public_table_counts']
    assert before['public_table_content_sha256']!=after['public_table_content_sha256']


@pytest.mark.parametrize('type_name,value', [
    ('jsonb', "'null'::jsonb"), ('jsonb', "'\"null\"'::jsonb"),
    ('jsonb', "'{}'::jsonb"), ('jsonb', "'[]'::jsonb"), ('json', "'null'::json"),
    ('text', "''"), ('int', '0'), ('bool', 'false'),
    ('int[]', 'ARRAY[]::int[]'), ('int[]', 'ARRAY[NULL]::int[]'),
    ('jsonb[]', "ARRAY['null'::jsonb]"),
])
def test_sql_null_is_distinct_from_every_persisted_non_null_value(parity_database, type_name, value):
    before = parity_database(f'CREATE TABLE null_probe(v {type_name}); INSERT INTO null_probe VALUES(NULL)')
    after = parity_database(f'UPDATE null_probe SET v={value}')
    assert before['public_table_counts'] == after['public_table_counts']
    assert before['public_columns'] == after['public_columns']
    assert before['public_table_content_sha256']['null_probe'] != after['public_table_content_sha256']['null_probe']
    with pytest.raises(recovery.RecoveryFailed):
        recovery.assert_manifest_parity(before, after)


def test_array_elements_sql_null_distinct_from_jsonb_null(parity_database):
    before = parity_database('CREATE TABLE null_probe(v jsonb[]); INSERT INTO null_probe VALUES(ARRAY[NULL]::jsonb[])')
    after = parity_database("UPDATE null_probe SET v=ARRAY['null'::jsonb]")
    assert before['public_table_content_sha256'] != after['public_table_content_sha256']


@pytest.mark.parametrize('change', [
    "SELECT setval('sequence_probe',77,true)",
    "SELECT setval('sequence_probe',1,true)",
    'ALTER SEQUENCE sequence_probe INCREMENT 2',
    'ALTER SEQUENCE sequence_probe CACHE 7',
    'ALTER SEQUENCE sequence_probe CYCLE',
])
def test_sequence_definition_and_runtime_mutations_detected(parity_database, change):
    before = parity_database('CREATE SEQUENCE sequence_probe')
    after = parity_database(change)
    assert before['public_table_content_sha256'] == after['public_table_content_sha256']
    assert before['public_columns'] == after['public_columns']
    assert before['public_sequences'] != after['public_sequences']
    with pytest.raises(recovery.RecoveryFailed):
        recovery.assert_manifest_parity(before, after)


def test_standalone_serial_identity_sequences_are_all_authority(parity_database):
    before = parity_database('CREATE SEQUENCE standalone START 19; CREATE TABLE serial_probe(id serial)')
    sequences = {s['name']: s for s in before['public_sequences']}
    assert set(sequences) == {'standalone', 'serial_probe_id_seq', 'outside_eight_id_seq'}
    assert sequences['standalone']['ownership'] == []
    assert sequences['standalone']['last_value'] == 19 and sequences['standalone']['is_called'] is False
    assert sequences['serial_probe_id_seq']['ownership'] == [dict(schema='public', table='serial_probe', column='id', dependency='a')]
    assert sequences['outside_eight_id_seq']['ownership'] == [dict(schema='public', table='outside_eight', column='id', dependency='i')]
    for omitted in sequences:
        after = deepcopy(before)
        after['public_sequences'] = [s for s in after['public_sequences'] if s['name'] != omitted]
        with pytest.raises(recovery.RecoveryFailed):
            recovery.assert_manifest_parity(before, after)


@pytest.fixture
def proxy_module():
    spec = importlib.util.spec_from_file_location("f15_pinned_proxy", ROOT / "scripts/f15/pinned-docker-proxy.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


CLI_REQUESTS = json.loads((ROOT / 'backend/tests/fixtures/f15-cli-2.120.0-create-requests.json').read_text())
SYNTHETIC_TARGET = dict(PGHOST='host.docker.internal', PGPORT='5432', PGUSER='postgres', PGDATABASE='postgres')


def request_for(mode, password):
    body = deepcopy(CLI_REQUESTS[mode])
    body['Env'] = [v if not v.startswith('PGPASSWORD=') else 'PGPASSWORD='+password for v in body['Env']]
    return body


def rewrite(proxy_module, body, password):
    return proxy_module.pinned_create(body, tag='mutable:test', image='sha256:'+'a'*64,
                                      password=password, label='synthetic', target=SYNTHETIC_TARGET)


@pytest.mark.parametrize('mode', ['roles', 'schema', 'data'])
@pytest.mark.parametrize('character', ['"', "'", '\\', '$', '`', ' ', '%', '&', ';'])
def test_cli_generated_password_export_removed_before_docker_create(proxy_module, mode, character):
    password = 'synthetic-start'+character+'synthetic-end'
    body = request_for(mode, password)
    actual = rewrite(proxy_module, body, password)
    assert actual['Cmd'] == ['-c', proxy_module.canonical_script(mode)]
    assert password not in ''.join(actual['Cmd'])
    assert actual['Env'].count('PGPASSWORD='+password) == 1
    assert actual['Image'] == 'sha256:'+'a'*64
    assert 'PGSSLMODE=verify-full' in actual['Env']
    assert actual['Labels']['glamgenius.f15.run'] == 'synthetic'
    assert 'default_transaction_read_only=on' in next(v for v in actual['Env'] if v.startswith('PGOPTIONS='))


@pytest.mark.parametrize('payload', [
    'echo "synthetic\\\"secret"', "echo 'synthetic'\\\"'secret'", "printf '%s%s' synthetic secret",
    'export BASH_ENV=/tmp/evil', 'pg_dump --schema-only; env',
])
def test_shell_reconstructed_secret_commands_fail_closed(proxy_module, payload):
    password = 'synthetic"secret'
    body = request_for('schema', password)
    body['Cmd'][2] += '\n'+payload
    with pytest.raises(ValueError, match='DUMP_COMMAND_REJECTED'):
        rewrite(proxy_module, body, password)


@pytest.mark.parametrize('extra', ['BASH_ENV=/tmp/evil', 'PGHOST=evil.example', 'EXTRA_FLAGS=; env', 'PGPASSWORD=duplicate'])
def test_untrusted_environment_is_refused(proxy_module, extra):
    body = request_for('data', 'synthetic')
    body['Env'].append(extra)
    with pytest.raises(ValueError, match='DUMP_ENVIRONMENT_REJECTED'):
        rewrite(proxy_module, body, 'synthetic')


@pytest.mark.parametrize('drift', [None, 'command', 'duplicate_password', 'image', 'label'])
def test_actual_container_inspection_requires_canonical_authority(proxy_module, monkeypatch, capsys, drift):
    import io
    password = 'synthetic"\\$` %&;secret'
    expected = rewrite(proxy_module, request_for('schema', password), password)
    actual = {'Image': expected['Image'], 'Config': deepcopy(expected)}
    if drift == 'command':
        actual['Config']['Cmd'][1] += '\necho "$PGPASSWORD"'
    elif drift == 'duplicate_password':
        actual['Config']['Env'].append('PGPASSWORD='+password)
    elif drift == 'image':
        actual['Image'] = 'sha256:'+'b'*64
    elif drift == 'label':
        actual['Config']['Labels']['glamgenius.f15.run'] = 'other'
    payload = json.dumps(actual).encode()
    response = io.BytesIO(b'HTTP/1.1 200 OK\r\nContent-Length: '+str(len(payload)).encode()+b'\r\n\r\n'+payload)
    class Pipe:
        def __enter__(self): return self
        def __exit__(self, *args): return False
        def write(self, value):
            assert password.encode() not in value
            return len(value)
        def read(self, size): return response.read(size)
    monkeypatch.setattr(proxy_module.io, 'FileIO', lambda *a: Pipe())
    state = proxy_module.State('pipe', 'mutable:test', expected['Image'], 'synthetic', SYNTHETIC_TARGET)
    state.password = password
    if drift is None:
        state.inspect_created('a'*64, expected, 'schema')
        proof = json.loads(capsys.readouterr().out)
        assert proof['canonical_dump_command_verified'] and proof['credential_present_in_container_cmd'] is False
        assert proof['password_environment_only']
    else:
        with pytest.raises(ValueError, match='CREATED_CONTAINER_AUTHORITY_REJECTED'):
            state.inspect_created('a'*64, expected, 'schema')


def test_proxy_refuses_other_images_or_unowned_containers(proxy_module):
    state = proxy_module.State("pipe", "tag", "sha256:" + "a" * 64, "run", SYNTHETIC_TARGET)
    assert not state.authorize("DELETE", "/v1.51/containers/" + "a" * 64)
    with pytest.raises(ValueError):
        proxy_module.pinned_create(dict(Image="other", Cmd=[]), tag="tag", image=state.image, password="synthetic", label="run", target=SYNTHETIC_TARGET)


@pytest.mark.asyncio
@pytest.mark.parametrize("alias", ["localhost", "127.0.0.1"])
async def test_connected_same_cluster_alias_is_rejected_before_any_insert(tmp_path, monkeypatch, alias):
    from tests.test_f15_recovery import write_fixture_export
    write_fixture_export(tmp_path)
    original = make_url(config.POSTGRES_URL)
    monkeypatch.setattr(config, "OFF_DATABASE_URL", original.set(host=alias).render_as_string(hide_password=False))
    monkeypatch.setattr(config, 'POSTGRES_URL', original.set(database='different_textual_database_test').render_as_string(hide_password=False))
    await store.dispose_off_engine()
    try:
        await store.create_off_schema()
        async with store.get_off_engine().begin() as connection:
            await connection.execute(text('TRUNCATE off_data.off_products'))
        from tests.f15_local_authority import restored_store_b_fixture
        with restored_store_b_fixture(monkeypatch) as (target, _):
            assert target.database != original.database
            with pytest.raises(importer.InvalidOffExport, match="physically separate"):
                await importer.import_export(tmp_path)
        async with store.get_off_engine().connect() as connection:
            assert (await connection.execute(text('SELECT count(*) FROM off_data.off_products'))).scalar_one() == 0
    finally:
        await store.dispose_off_engine()


@pytest.mark.asyncio
async def test_importer_missing_cluster_authority_fails_before_session(tmp_path, monkeypatch):
    from tests.test_f15_recovery import write_fixture_export
    write_fixture_export(tmp_path)
    original = make_url(config.POSTGRES_URL)
    monkeypatch.setattr(config, "OFF_DATABASE_URL", original.set(port=5433).render_as_string(hide_password=False))
    monkeypatch.setattr(importer, "get_off_sessionmaker", lambda: pytest.fail("Acquired a session without authority"))
    monkeypatch.delenv(local_recovery.LOCAL_STORE_B_URL_ENV, raising=False)
    with pytest.raises(importer.InvalidOffExport, match="cluster authority"):
        await importer.import_export(tmp_path)


def test_invented_identifier_api_and_cli_surface_absent():
    import inspect
    assert list(inspect.signature(importer.import_export).parameters) == ['directory']
    assert '--store-b-system-identifier' not in inspect.getsource(importer.main)


@pytest.mark.asyncio
@pytest.mark.parametrize('bad', ['https://db.example/postgres', 'postgresql://postgres@db.example/postgres',
                                 'postgresql://postgres@127.0.0.1/postgres?host=evil.example'])
async def test_nonlocal_store_b_refused_before_engine_creation(monkeypatch, bad):
    monkeypatch.setenv(local_recovery.LOCAL_STORE_B_URL_ENV, bad)
    monkeypatch.setattr(local_recovery, 'create_async_engine', lambda *a, **k: pytest.fail('Nonlocal connection attempted'))
    with pytest.raises(local_recovery.LocalRecoveryAuthorityError):
        await local_recovery.restored_store_b_authority()


@pytest.mark.asyncio
@pytest.mark.parametrize('drift', ["UPDATE alembic_version SET version_num='wrong'", 'DROP TABLE accounts', 'CREATE SCHEMA off_data',
                                  'GRANT UPDATE ON public.accounts TO f15_fixture_identity_reader',
                                  'GRANT UPDATE(id) ON public.accounts TO f15_fixture_identity_reader'])
async def test_wrong_restored_store_b_authority_refused(monkeypatch, drift):
    from tests.f15_local_authority import restored_store_b_fixture
    with restored_store_b_fixture(monkeypatch) as (_, sql):
        sql(drift)
        with pytest.raises(local_recovery.LocalRecoveryAuthorityError, match='mismatch'):
            await local_recovery.restored_store_b_authority()


def test_operator_source_table_authority_matches_importer():
    assert tuple(json.loads((ROOT / 'backend/app/operations/accepted_store_b_public_tables.json').read_text())) == local_recovery.EXPECTED_TABLES


@pytest.mark.asyncio
async def test_store_b_unavailable_identity_fails_closed(monkeypatch):
    from tests.f15_local_authority import restored_store_b_fixture
    with restored_store_b_fixture(monkeypatch) as (_, sql):
        sql('REVOKE EXECUTE ON FUNCTION pg_catalog.pg_control_system() FROM PUBLIC,f15_fixture_identity_reader')
        with pytest.raises(local_recovery.LocalRecoveryAuthorityError):
            await local_recovery.restored_store_b_authority()


@pytest.mark.asyncio
async def test_store_b_catalog_identity_cannot_be_shadowed(monkeypatch):
    from tests.f15_local_authority import restored_store_b_fixture
    with restored_store_b_fixture(monkeypatch) as (_, sql):
        expected = sql('SELECT system_identifier::text FROM pg_catalog.pg_control_system()').strip()
        sql("CREATE FUNCTION public.pg_control_system() RETURNS TABLE(system_identifier bigint) LANGUAGE sql AS $$ SELECT 10000000000::bigint $$;"
            "ALTER ROLE f15_fixture_identity_reader SET search_path=public,pg_catalog")
        actual = await local_recovery.restored_store_b_authority()
        assert actual['system_identifier'] == expected and actual['system_identifier'] != '10000000000'


@pytest.mark.asyncio
async def test_store_a_unavailable_identity_fails_before_insert(monkeypatch, tmp_path):
    from tests.f15_local_authority import restored_store_b_fixture
    from tests.test_f15_recovery import write_fixture_export
    write_fixture_export(tmp_path)
    original = make_url(config.POSTGRES_URL)
    monkeypatch.setattr(config, 'OFF_DATABASE_URL', original.render_as_string(hide_password=False))
    monkeypatch.setattr(config, 'POSTGRES_URL', original.set(database='different_textual_database_test').render_as_string(hide_password=False))
    monkeypatch.setattr(importer, 'text', lambda query: text('SELECT NULL::text') if 'pg_control_system' in query else text(query))
    await store.dispose_off_engine()
    try:
        await store.create_off_schema()
        async with store.get_off_engine().begin() as connection:
            await connection.execute(text('TRUNCATE off_data.off_products'))
        with restored_store_b_fixture(monkeypatch), pytest.raises(importer.InvalidOffExport, match='physically separate'):
            await importer.import_export(tmp_path)
        async with store.get_off_engine().connect() as connection:
            assert (await connection.execute(text('SELECT count(*) FROM off_data.off_products'))).scalar_one() == 0
    finally:
        await store.dispose_off_engine()


@pytest.mark.asyncio
async def test_connected_store_b_identity_operation_read_only(monkeypatch):
    from sqlalchemy.ext.asyncio import create_async_engine

    from tests.f15_local_authority import restored_store_b_fixture
    with restored_store_b_fixture(monkeypatch) as (target, _):
        authority = await local_recovery.restored_store_b_authority()
        assert authority['transaction_read_only'] and authority['default_transaction_read_only']
        assert authority['production_session'] is False
        assert authority['role_write_capability'] is False
        engine = create_async_engine(target, connect_args={'server_settings': {'default_transaction_read_only': 'on'}})
        try:
            async with engine.connect() as connection:
                connection = await connection.execution_options(isolation_level='REPEATABLE READ', postgresql_readonly=True)
                async with connection.begin():
                    assert (await connection.execute(text('SHOW transaction_read_only'))).scalar_one() == 'on'
                    with pytest.raises(Exception, match='read-only transaction|permission denied'):
                        await connection.execute(text("UPDATE public.alembic_version SET version_num='write-denied'"))
        finally:
            await engine.dispose()
