"""Synthetic late-review regressions; never production recovery evidence."""
from __future__ import annotations

import hashlib
import importlib.util
import json
import os
from copy import deepcopy
from pathlib import Path

import pytest
from app import config
from app.domains.off import importer, store
from app.operations import recovery
from sqlalchemy import text
from sqlalchemy.engine import make_url

ROOT = Path(__file__).resolve().parents[2]


@pytest.mark.parametrize("problem", ["duplicate", "key", "source_size", "source_digest", "missing", "extra", "recovered_digest"])
def test_object_proofs_are_exactly_bound_to_independent_source(problem):
    key = hashlib.sha256(b"synthetic/object").hexdigest()
    digest = hashlib.sha256(b"synthetic bytes").hexdigest()
    source = {"storage_objects": 1, "storage_byte_manifest": [{"key_sha256": key, "bytes": 15, "sha256": digest}]}
    proof = recovery.ByteRecovery(15, digest, key, 15, digest)
    recovery.assert_storage_proofs(source, [proof])
    values = dict(bytes=15, sha256=digest, source_key_sha256=key, source_bytes=15, source_sha256=digest)
    if problem == "key":
        values["source_key_sha256"] = "a" * 64
    elif problem == "source_size":
        values["source_bytes"] = 16
    elif problem == "source_digest":
        values["source_sha256"] = "a" * 64
    elif problem == "recovered_digest":
        values["sha256"] = "a" * 64
    proofs = [recovery.ByteRecovery(**values)]
    if problem in {"duplicate", "extra"}:
        proofs.append(proof)
    elif problem == "missing":
        proofs = []
    with pytest.raises(recovery.RecoveryFailed):
        recovery.assert_storage_proofs(source, proofs)


def test_zero_source_refuses_extra_fake_storage_proof():
    with pytest.raises(recovery.RecoveryFailed):
        recovery.assert_storage_proofs({"storage_objects": 0}, [recovery.ByteRecovery(1, "a" * 64, "b" * 64, 1, "a" * 64)])


@pytest.fixture
def parity_database():
    url = make_url(os.environ["POSTGRES_URL"]).set(drivername="postgresql", database="f15_manifest_test")
    admin = url.set(database="postgres")
    env = dict(os.environ, PGPASSWORD=url.password or "")
    def sql(query, *, database=url):
        return recovery.run_checked(["psql", "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-v", "SHOW_CONTEXT=never",
                                     "--dbname", database.set(password=None).render_as_string(hide_password=False), "-c", query], environment=env)
    exists = sql("SELECT EXISTS(SELECT FROM pg_database WHERE datname='f15_manifest_test')", database=admin).strip()
    if exists == "f":
        sql('CREATE DATABASE f15_manifest_test', database=admin)
    sql("""DROP SCHEMA public CASCADE; CREATE SCHEMA public;
        CREATE SCHEMA IF NOT EXISTS extensions; CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
        CREATE SCHEMA IF NOT EXISTS auth; CREATE TABLE IF NOT EXISTS auth.users(id int);
        CREATE SCHEMA IF NOT EXISTS storage; CREATE TABLE IF NOT EXISTS storage.objects(id int);
        CREATE TABLE IF NOT EXISTS storage.buckets(id int);
        CREATE SCHEMA IF NOT EXISTS vault; CREATE TABLE IF NOT EXISTS vault.secrets(id int);
        CREATE TABLE public.alembic_version(version_num text); INSERT INTO public.alembic_version VALUES('d0e1f2g3h4');
        CREATE TABLE public.accounts(id text); CREATE TABLE public.external_integrations(id text);
        CREATE TABLE public.inventory_items(id text); CREATE TABLE public.invites(id text);
        CREATE TABLE public.media_assets(id text); CREATE TABLE public.product_records(id text);
        CREATE TABLE public.scan_devices(id text); CREATE TABLE public.scans(id text);
        CREATE TABLE public.outside_eight(id integer GENERATED BY DEFAULT AS IDENTITY,
          value text NOT NULL DEFAULT 'fixture', j json, jb jsonb, n numeric, b bool, optional text,
          t timestamptz, d date, computed integer GENERATED ALWAYS AS (id+1) STORED);
        INSERT INTO public.outside_eight(value,j,jb,n,b,optional,t,d) VALUES
          ('private synthetic only','{ "a":1 }','{"a":1}',42.50,true,NULL,'2020-01-02 03:04:05+00','2020-01-02');
    """)
    query = (ROOT / "scripts/f15/safe-source-manifest.sql").read_text(encoding="utf-8")
    def manifest(change=""):
        # The mutation commits only to this named synthetic fixture database.
        if change:
            sql(change)
        return json.loads(sql(query))
    yield manifest
    sql("DROP SCHEMA public CASCADE; CREATE SCHEMA public")


@pytest.mark.parametrize("change", [
    "UPDATE outside_eight SET value='different'",
    "UPDATE outside_eight SET j='{\"a\":2}'",
    "UPDATE outside_eight SET jb='{\"a\":2}'",
    "UPDATE outside_eight SET n=42.51",
    "UPDATE outside_eight SET b=false",
    "UPDATE outside_eight SET optional=''",
    "UPDATE outside_eight SET t=t+interval '1 second'",
    "UPDATE outside_eight SET d=d+1",
])
def test_complete_non_id_row_mutants_detected(parity_database, change):
    before = parity_database()
    after = parity_database(change)
    assert before["public_table_counts"] == after["public_table_counts"]
    assert before["sorted_primary_id_sha256"] == after["sorted_primary_id_sha256"]
    assert before["public_table_content_sha256"]["outside_eight"] != after["public_table_content_sha256"]["outside_eight"]
    with pytest.raises(recovery.RecoveryFailed, match="MANIFEST_MISMATCH"):
        recovery.assert_manifest_parity(before, after)


@pytest.mark.parametrize("change", [
    "ALTER TABLE outside_eight ALTER COLUMN value DROP NOT NULL",
    "ALTER TABLE outside_eight ALTER COLUMN value SET DEFAULT 'changed'",
    "ALTER TABLE outside_eight ALTER COLUMN value TYPE varchar(100)",
    "ALTER TABLE outside_eight DROP COLUMN computed; ALTER TABLE outside_eight ADD COLUMN computed int GENERATED ALWAYS AS(id+2) STORED",
    "ALTER TABLE outside_eight ALTER COLUMN id SET GENERATED ALWAYS",
])
def test_complete_column_authority_mutants_detected(parity_database, change):
    before = parity_database()
    after = parity_database(change)
    assert before["public_columns"] != after["public_columns"]
    with pytest.raises(recovery.RecoveryFailed, match="MANIFEST_MISMATCH"):
        recovery.assert_manifest_parity(before, after)


def test_unsupported_type_fails_even_on_empty_table(parity_database):
    with pytest.raises(recovery.RecoveryFailed):
        parity_database("CREATE TABLE unsupported(value xml)")


def test_logical_column_order_survives_dropped_slots_and_rejects_reordering(parity_database):
    before = parity_database("""CREATE TABLE ordinal_gap(first integer, discarded text, last text);
        ALTER TABLE ordinal_gap DROP COLUMN discarded;
        INSERT INTO ordinal_gap(first,last) VALUES (7,'synthetic');""")
    # Replay the visible schema exactly as a logical dump does, without the
    # source's invisible dropped-column slot.
    compacted = parity_database("""DROP TABLE ordinal_gap;
        CREATE TABLE ordinal_gap(first integer, last text);
        INSERT INTO ordinal_gap(first,last) VALUES (7,'synthetic');""")
    assert [c["attnum"] for c in before["public_columns"] if c["table"] == "ordinal_gap"] == [1, 2]
    assert before["public_columns"] == compacted["public_columns"]
    recovery.assert_manifest_parity(before, compacted)
    reordered = parity_database("""DROP TABLE ordinal_gap;
        CREATE TABLE ordinal_gap(last text, first integer);
        INSERT INTO ordinal_gap(first,last) VALUES (7,'synthetic');""")
    assert before["public_columns"] != reordered["public_columns"]
    with pytest.raises(recovery.RecoveryFailed, match="MANIFEST_MISMATCH"):
        recovery.assert_manifest_parity(before, reordered)


def test_row_multiset_preserves_duplicates_and_ignores_order(parity_database):
    before = parity_database("CREATE TABLE duplicate_probe(v text); INSERT INTO duplicate_probe VALUES ('a'),('b'),('a')")
    reordered = parity_database("TRUNCATE duplicate_probe; INSERT INTO duplicate_probe VALUES ('a'),('a'),('b')")
    assert before["public_table_content_sha256"] == reordered["public_table_content_sha256"]
    changed = parity_database("TRUNCATE duplicate_probe; INSERT INTO duplicate_probe VALUES ('b'),('a'),('b')")
    assert before["public_table_content_sha256"] != changed["public_table_content_sha256"]


def test_generated_expression_same_ordinal_is_detected(parity_database):
    before=parity_database()
    if before["server_version"].split('.')[0] != '17':
        pytest.skip('PG17 SET EXPRESSION regression; PG16 drop/recreate covered separately')
    after=parity_database("ALTER TABLE outside_eight ALTER COLUMN computed SET EXPRESSION AS (id+2)")
    source=next(c for c in before['public_columns'] if c['column']=='computed')
    target=next(c for c in after['public_columns'] if c['column']=='computed')
    assert source['attnum'] == target['attnum']
    assert source['default_expression_sha256'] != target['default_expression_sha256']


def test_array_lower_bounds_are_part_of_complete_content(parity_database):
    before=parity_database("CREATE TABLE array_probe(v int[]); INSERT INTO array_probe VALUES ('[0:1]={1,2}')")
    after=parity_database("UPDATE array_probe SET v=ARRAY[1,2]")
    assert before['public_table_counts']==after['public_table_counts']
    assert before['public_table_content_sha256']!=after['public_table_content_sha256']


@pytest.fixture
def proxy_module():
    spec = importlib.util.spec_from_file_location("f15_pinned_proxy", ROOT / "scripts/f15/pinned-docker-proxy.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_cli_generated_password_export_removed_before_docker_create(proxy_module):
    import secrets
    password = secrets.token_hex(24)
    body = dict(Image="mutable:test", Cmd=["bash", "-c", f'export PGPASSWORD="{password}"\npg_dump --schema-only'], Env=[])
    actual = proxy_module.pinned_create(body, tag="mutable:test", image="sha256:" + "a" * 64, password=password, label="synthetic")
    assert password not in json.dumps(actual["Cmd"])
    assert "PGPASSWORD=" + password in actual["Env"]
    assert actual["Image"] == "sha256:" + "a" * 64
    assert "PGSSLMODE=verify-full" in actual["Env"]
    bad = deepcopy(body)
    bad["Cmd"][2] += f'\necho "{password}"'
    with pytest.raises(ValueError, match="SECRET_COMMAND_REJECTED"):
        proxy_module.pinned_create(bad, tag="mutable:test", image="sha256:" + "a" * 64, password=password, label="synthetic")


def test_proxy_refuses_other_images_or_unowned_containers(proxy_module):
    state = proxy_module.State("pipe", "tag", "sha256:" + "a" * 64, "run")
    assert not state.authorize("DELETE", "/v1.51/containers/" + "a" * 64)
    with pytest.raises(ValueError):
        proxy_module.pinned_create(dict(Image="other", Cmd=[]), tag="tag", image=state.image, password="synthetic", label="run")


@pytest.mark.asyncio
@pytest.mark.parametrize("alias", ["localhost", "127.0.0.1", "db.local"])
async def test_connected_same_cluster_alias_is_rejected_before_any_insert(tmp_path, monkeypatch, alias):
    from tests.test_f15_recovery import write_fixture_export
    write_fixture_export(tmp_path)
    original = make_url(config.POSTGRES_URL)
    monkeypatch.setattr(config, "POSTGRES_URL", original.set(host=alias, database="different_textual_database").render_as_string(hide_password=False))
    monkeypatch.setattr(config, "OFF_DATABASE_URL", original.set(host="127.0.0.1").render_as_string(hide_password=False))
    await store.dispose_off_engine()
    try:
        async with store.get_off_engine().connect() as connection:
            actual = (await connection.execute(text("SELECT system_identifier::text FROM pg_control_system()"))).scalar_one()
        with pytest.raises(importer.InvalidOffExport, match="physically separate"):
            await importer.import_export(tmp_path, store_b_system_identifier=actual)
    finally:
        await store.dispose_off_engine()


@pytest.mark.asyncio
async def test_importer_missing_cluster_authority_fails_before_session(tmp_path, monkeypatch):
    from tests.test_f15_recovery import write_fixture_export
    write_fixture_export(tmp_path)
    original = make_url(config.POSTGRES_URL)
    monkeypatch.setattr(config, "OFF_DATABASE_URL", original.set(port=5433).render_as_string(hide_password=False))
    monkeypatch.setattr(importer, "get_off_sessionmaker", lambda: pytest.fail("Acquired a session without authority"))
    with pytest.raises(importer.InvalidOffExport, match="cluster authority"):
        await importer.import_export(tmp_path)
