import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';

import { EstimateNotice, InventoryItemCard, InventoryRecovery } from '../src/components/inventory/InventoryPieces';
import { DuplicateCandidate, InventoryItem, ValueToRecover, getExpiringInventory, getInventoryDuplicates, getLowUseInventory, getValueToRecover, resolveInventoryDuplicate } from '../src/services/apiV2';
import { COLORS, FONTS, RADIUS, SPACING } from '../src/theme/colors';

type ViewName = 'low-use' | 'expiring' | 'duplicates' | 'value';
const TITLES: Record<ViewName, string> = { 'low-use': 'Low-Use Products', expiring: 'Products Expiring Soon', duplicates: 'Duplicate Candidates', value: 'Value to Recover' };

export default function InventoryInsightsScreen() {
  const params = useLocalSearchParams<{ view?: string }>(); const view = (Object.keys(TITLES).includes(params.view || '') ? params.view : 'low-use') as ViewName;
  const router = useRouter(); const insets = useSafeAreaInsets(); const [items, setItems] = useState<InventoryItem[]>([]); const [duplicates, setDuplicates] = useState<DuplicateCandidate[]>([]); const [value, setValue] = useState<ValueToRecover | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(false); try { if (view === 'low-use') setItems(await getLowUseInventory()); else if (view === 'expiring') setItems(await getExpiringInventory()); else if (view === 'duplicates') setDuplicates(await getInventoryDuplicates()); else setValue(await getValueToRecover()); } catch (err) { console.warn('inventory insight load failed', err); setError(true); } finally { setLoading(false); } }, [view]);
  useEffect(() => { void load(); }, [load]);
  const resolve = async (candidate: DuplicateCandidate, resolution: 'keep_both' | 'not_duplicate' | 'merge', canonical?: string) => { await resolveInventoryDuplicate(candidate.id, resolution, canonical); setDuplicates((rows) => rows.filter((row) => row.id !== candidate.id)); };
  if (loading) return <View style={styles.center}><ActivityIndicator color={COLORS.primary} /></View>;
  if (error) return <View style={styles.center}><InventoryRecovery onRetry={() => void load()} onAdd={() => router.replace('/inventory-add')} /></View>;
  return <View style={[styles.container, { paddingTop: insets.top }]}><View style={styles.top}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Back to inventory" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={COLORS.textPrimary} /></TouchableOpacity><Text style={styles.topTitle}>{TITLES[view]}</Text><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={{ padding: SPACING.lg, paddingBottom: insets.bottom + 40 }}>
    <Text style={styles.eyebrow}>INVENTORY INTELLIGENCE</Text><Text style={styles.title}>{TITLES[view]}</Text>
    {view === 'low-use' && <Text style={styles.body}>Items at least 30 days old, used no more than twice and not used in the last 30 days.</Text>}
    {view === 'expiring' && <Text style={styles.body}>Deterministic dates use the entered expiry and period-after-opening information.</Text>}
    {view === 'duplicates' && <Text style={styles.body}>Review similar entries. Nothing is merged without your choice.</Text>}
    {view === 'value' && value && <><Text style={styles.total}>₹{value.estimated_total.toLocaleString('en-IN')}</Text><Text style={styles.estimate}>Estimated total · {value.metric_version}</Text><EstimateNotice explanation={value.explanation} />{value.items.map((row) => <View key={row.item_id} style={styles.valueRow}><View style={{ flex: 1 }}><Text style={styles.itemName}>{row.display_name}</Text><Text style={styles.itemMeta}>{row.missing_inputs.length ? 'Add price for an estimate' : 'Estimate, not an exact value'}</Text></View><Text style={styles.itemValue}>{row.estimated_value == null ? '—' : `₹${row.estimated_value.toLocaleString('en-IN')}`}</Text></View>)}</>}
    {view !== 'value' && view !== 'duplicates' && (items.length ? items.map((item) => <InventoryItemCard key={item.id} item={item} onPress={() => router.push({ pathname: '/inventory-item', params: { id: item.id } })} />) : <Empty />)}
    {view === 'duplicates' && (duplicates.length ? duplicates.map((candidate) => <View key={candidate.id} style={styles.dupe}><Text style={styles.itemName}>{candidate.item_a.display_name} · {candidate.item_b.display_name}</Text><Text style={styles.itemMeta}>{candidate.reason} · {Math.round(candidate.confidence * 100)}% match</Text><View style={styles.dupeActions}><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Keep both ${candidate.item_a.display_name} and ${candidate.item_b.display_name}`} onPress={() => void resolve(candidate, 'keep_both')} style={styles.outline}><Text style={styles.outlineText}>Keep both</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Merge into ${candidate.item_a.display_name}`} onPress={() => void resolve(candidate, 'merge', candidate.item_a.id)} style={styles.primary}><Text style={styles.primaryText}>Merge</Text></TouchableOpacity></View></View>) : <Empty />)}
  </ScrollView></View>;
}

function Empty() { return <View style={styles.empty}><Ionicons name="checkmark-circle-outline" size={30} color={COLORS.success} /><Text style={styles.itemName}>Nothing needs attention here</Text></View>; }
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundSecondary }, center: { flex: 1, backgroundColor: COLORS.background, alignItems: 'center', justifyContent: 'center' }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: SPACING.lg, paddingVertical: 12 }, topTitle: { fontFamily: FONTS.family.bodySemibold, color: COLORS.textPrimary }, eyebrow: { fontFamily: FONTS.family.bodySemibold, color: COLORS.primary, fontSize: 10, letterSpacing: 1.3 }, title: { fontFamily: FONTS.family.heading, color: COLORS.textPrimary, fontSize: 29, marginTop: 5, marginBottom: 6 }, body: { fontFamily: FONTS.family.body, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, marginBottom: 18 }, total: { fontFamily: FONTS.family.heading, color: COLORS.textPrimary, fontSize: 36, marginTop: 12 }, estimate: { fontFamily: FONTS.family.bodyMedium, color: COLORS.textMuted, fontSize: 11, marginBottom: 14 }, valueRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.card, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border, padding: 13, marginTop: 8 }, itemName: { fontFamily: FONTS.family.bodySemibold, color: COLORS.textPrimary, fontSize: 13 }, itemMeta: { fontFamily: FONTS.family.body, color: COLORS.textMuted, fontSize: 10, marginTop: 4 }, itemValue: { fontFamily: FONTS.family.headingMedium, color: COLORS.primary, fontSize: 17 }, dupe: { backgroundColor: COLORS.card, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: COLORS.border, padding: 14, marginTop: 10 }, dupeActions: { flexDirection: 'row', gap: 9, marginTop: 13 }, outline: { flex: 1, borderWidth: 1, borderColor: COLORS.primary, borderRadius: RADIUS.full, alignItems: 'center', padding: 10 }, outlineText: { fontFamily: FONTS.family.bodySemibold, color: COLORS.primary, fontSize: 11 }, primary: { flex: 1, borderRadius: RADIUS.full, backgroundColor: COLORS.primary, alignItems: 'center', padding: 10 }, primaryText: { fontFamily: FONTS.family.bodySemibold, color: COLORS.white, fontSize: 11 }, empty: { alignItems: 'center', gap: 9, padding: SPACING.xl, backgroundColor: COLORS.card, borderRadius: RADIUS.lg, marginTop: 15 },
});
