import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';

import { CATEGORY_META, DraftReviewActions, InventoryRecovery } from '../src/components/inventory/InventoryPieces';
import { CareExperienceFeedbackSheet, canRecordCareExperienceForCategory } from '../src/components/routines/CareExperienceFeedback';
import { InventoryItem, confirmInventoryItem, deleteInventoryItem, getInventoryItem, logInventoryUsage, patchInventoryItem, setInventoryCondition } from '../src/services/apiV2';
import { errorMessage } from '../src/services/api';
import { COLORS, FONTS, RADIUS, SPACING } from '../src/theme/colors';

export default function InventoryItemScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const insets = useSafeAreaInsets();
  const [item, setItem] = useState<InventoryItem | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [editing, setEditing] = useState(false);
  const [name, setName] = useState(''); const [brand, setBrand] = useState(''); const [expiry, setExpiry] = useState(''); const [message, setMessage] = useState(''); const [feedbackOpen, setFeedbackOpen] = useState(false);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(false); try { const next = await getInventoryItem(id); setItem(next); setName(next.display_name); setBrand(next.brand || ''); setExpiry(next.effective_expiry || ''); } catch (err) { console.warn('inventory item load failed', err); setError(true); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { if (!item) return; setMessage(''); try { const details = ['beauty', 'hair', 'supplements'].includes(item.category) && expiry ? { expiry_date: expiry } : {}; const next = await patchInventoryItem(item.id, { expected_version: item.version, display_name: name, brand, details }); setItem(next); setEditing(false); } catch (err) { setMessage(errorMessage(err, 'Could not save. Refresh the item and try again.')); } };
  const confirm = async () => { if (!item) return; try { setItem(await confirmInventoryItem(item.id)); } catch (err) { setMessage(errorMessage(err, 'Could not confirm this draft.')); } };
  const used = async () => { if (!item) return; try { setItem(await logInventoryUsage(item.id, new Date().toISOString().slice(0, 10))); } catch (err) { setMessage(errorMessage(err, 'Could not log usage.')); } };
  const condition = async (value: string) => { if (!item) return; try { setItem(await setInventoryCondition(item.id, value)); } catch (err) { setMessage(errorMessage(err, 'Could not update condition.')); } };
  const remove = () => item && Alert.alert('Remove this item?', 'It will leave active inventory, while its history is retained.', [{ text: 'Keep item', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => void deleteInventoryItem(item.id).then(() => router.replace('/(tabs)/inventory')) }]);
  if (loading) return <View style={styles.center}><ActivityIndicator color={COLORS.primary} /></View>;
  if (error || !item) return <View style={styles.center}><InventoryRecovery onRetry={() => void load()} onAdd={() => router.replace('/inventory-add')} /></View>;
  const detailEntries = Object.entries(item.details).filter(([key]) => key !== 'safety_disclaimer');
  const careItem = canRecordCareExperienceForCategory(item.category);
  return <View style={[styles.container, { paddingTop: insets.top }]}><View style={styles.top}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Back to inventory" onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)/inventory')}><Ionicons name="arrow-back" size={24} color={COLORS.textPrimary} /></TouchableOpacity><Text style={styles.topTitle}>Item details</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Edit ${item.display_name}`} onPress={() => setEditing(!editing)}><Text style={styles.edit}>{editing ? 'Cancel' : 'Edit'}</Text></TouchableOpacity></View><ScrollView contentContainerStyle={{ padding: SPACING.lg, paddingBottom: insets.bottom + 50 }}>
    {item.verification_state === 'draft' && <DraftReviewActions item={item} onConfirm={() => void confirm()} onEdit={() => setEditing(true)} />}
    <View style={styles.hero}><View style={styles.heroIcon}><Ionicons name={CATEGORY_META[item.category].icon as any} size={30} color={COLORS.primary} /></View><Text style={styles.category}>{CATEGORY_META[item.category].label.toUpperCase()}</Text><Text style={styles.title}>{item.display_name}</Text><Text style={styles.brand}>{item.brand || 'Brand not added'}</Text></View>
    {editing ? <View style={styles.card}><Text style={styles.label}>Item name</Text><TextInput accessibilityLabel="Edit item name" value={name} onChangeText={setName} style={styles.input} /><Text style={styles.label}>Brand</Text><TextInput accessibilityLabel="Edit item brand" value={brand} onChangeText={setBrand} style={styles.input} />{['beauty', 'hair', 'supplements'].includes(item.category) && <><Text style={styles.label}>Expiry date</Text><TextInput accessibilityLabel="Edit expiry date" value={expiry} onChangeText={setExpiry} placeholder="YYYY-MM-DD" style={styles.input} /></>}<TouchableOpacity accessibilityRole="button" accessibilityLabel="Save item corrections" onPress={() => void save()} style={styles.primary}><Text style={styles.primaryText}>Save corrections</Text></TouchableOpacity></View> : <>
      <View style={styles.actionRow}><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Log usage for ${item.display_name}`} onPress={() => void used()} style={styles.action}><Ionicons name="checkmark-circle-outline" size={20} color={COLORS.primary} /><Text style={styles.actionText}>Used today</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Mark ${item.display_name} needing attention`} onPress={() => void condition('needs_attention')} style={styles.action}><Ionicons name="construct-outline" size={20} color={COLORS.warning} /><Text style={styles.actionText}>Needs attention</Text></TouchableOpacity></View>
      <Text style={styles.section}>Item facts</Text><View style={styles.card}><Fact label="Condition" value={item.condition} /><Fact label="Times used" value={String(item.usage_count)} /><Fact label="Last used" value={item.last_used_at || 'Not logged yet'} />{item.effective_expiry && <Fact label="Effective expiry" value={item.effective_expiry} />}{detailEntries.map(([key, value]) => <Fact key={key} label={key.replaceAll('_', ' ')} value={Array.isArray(value) ? value.join(', ') : String(value)} />)}</View>
      {careItem && <View style={styles.experienceCard}><Text style={styles.section}>Your experience</Text><Text style={styles.experienceBody}>Record your experience with this product. Your routine will not change automatically.</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Record experience" onPress={() => setFeedbackOpen(true)} style={styles.experienceButton}><Text style={styles.experienceButtonText}>Record experience</Text><Ionicons name="arrow-forward" size={16} color={COLORS.primary} /></TouchableOpacity></View>}
      {item.attributes.length > 0 && <><Text style={styles.section}>Source and confidence</Text><View style={styles.card}>{item.attributes.map((row) => <Fact key={row.key} label={`${row.key.replaceAll('_', ' ')} · ${Math.round(row.confidence * 100)}% · ${row.verification_state}`} value={Array.isArray(row.value) ? row.value.join(', ') : String(row.value)} />)}</View></>}
      {item.category === 'supplements' && <Text style={styles.safety}>{item.details.safety_disclaimer}</Text>}
      <Text style={styles.section}>History</Text><View style={styles.card}>{item.history?.map((event, index) => <Fact key={`${event.event_type}-${index}`} label={event.event_type.replaceAll('_', ' ')} value={event.created_at?.slice(0, 10) || ''} />)}</View>
      <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Remove ${item.display_name}`} onPress={remove}><Text style={styles.remove}>Remove from active inventory</Text></TouchableOpacity>
    </>}
    {!!message && <Text accessibilityRole="alert" style={styles.error}>{message}</Text>}
  </ScrollView>{careItem && <CareExperienceFeedbackSheet open={feedbackOpen} subjectType="product" subjectId={item.id} subjectLabel={item.display_name} onClose={() => setFeedbackOpen(false)} />}</View>;
}

function Fact({ label, value }: { label: string; value: string }) { return <View style={styles.fact}><Text style={styles.factLabel}>{label}</Text><Text style={styles.factValue}>{value}</Text></View>; }
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundSecondary }, center: { flex: 1, backgroundColor: COLORS.background, alignItems: 'center', justifyContent: 'center' }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: SPACING.lg, paddingVertical: 12 }, topTitle: { fontFamily: FONTS.family.bodySemibold, color: COLORS.textPrimary }, edit: { fontFamily: FONTS.family.bodySemibold, color: COLORS.primary, width: 48, textAlign: 'right' }, hero: { alignItems: 'center', paddingVertical: 22 }, heroIcon: { width: 64, height: 64, borderRadius: 20, backgroundColor: COLORS.primaryLight, alignItems: 'center', justifyContent: 'center' }, category: { fontFamily: FONTS.family.bodySemibold, color: COLORS.primary, fontSize: 9, letterSpacing: 1.2, marginTop: 12 }, title: { fontFamily: FONTS.family.heading, color: COLORS.textPrimary, fontSize: 28, textAlign: 'center', marginTop: 4 }, brand: { fontFamily: FONTS.family.body, color: COLORS.textMuted, fontSize: 12, marginTop: 4 },
  actionRow: { flexDirection: 'row', gap: 10 }, action: { flex: 1, backgroundColor: COLORS.card, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border, padding: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7 }, actionText: { fontFamily: FONTS.family.bodySemibold, color: COLORS.textPrimary, fontSize: 11 }, section: { fontFamily: FONTS.family.headingMedium, color: COLORS.textPrimary, fontSize: 19, marginTop: 23, marginBottom: 9 }, card: { backgroundColor: COLORS.card, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: COLORS.border, paddingHorizontal: 14, paddingBottom: 12 }, experienceCard: { marginTop: 2 }, experienceBody: { fontFamily: FONTS.family.body, color: COLORS.textSecondary, fontSize: 12, lineHeight: 18 }, experienceButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: COLORS.primaryLight, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.primaryMuted, padding: 13, marginTop: 10 }, experienceButtonText: { fontFamily: FONTS.family.bodySemibold, color: COLORS.primary, fontSize: 12 }, fact: { paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: COLORS.border }, factLabel: { fontFamily: FONTS.family.bodyMedium, color: COLORS.textMuted, fontSize: 10, textTransform: 'capitalize' }, factValue: { fontFamily: FONTS.family.bodySemibold, color: COLORS.textPrimary, fontSize: 13, marginTop: 3, textTransform: 'capitalize' }, label: { fontFamily: FONTS.family.bodySemibold, color: COLORS.textPrimary, fontSize: 11, marginTop: 12, marginBottom: 5 }, input: { borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, backgroundColor: COLORS.background, padding: 11, fontFamily: FONTS.family.body, color: COLORS.textPrimary }, primary: { backgroundColor: COLORS.primary, borderRadius: RADIUS.full, alignItems: 'center', padding: 13, marginTop: 17 }, primaryText: { fontFamily: FONTS.family.bodySemibold, color: COLORS.white }, safety: { backgroundColor: COLORS.infoLight, borderRadius: RADIUS.md, padding: 12, fontFamily: FONTS.family.body, color: COLORS.textSecondary, fontSize: 11, lineHeight: 17, marginTop: 18 }, remove: { fontFamily: FONTS.family.bodySemibold, color: COLORS.error, textAlign: 'center', marginTop: 25 }, error: { fontFamily: FONTS.family.bodyMedium, color: COLORS.error, textAlign: 'center', marginTop: 15 },
});
