"""Complete appearance inventory.

Revision ID: 0003_complete_inventory
Revises: 0002_appearance_digital_twin
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0003_complete_inventory"
down_revision = "0002_appearance_digital_twin"
branch_labels = None
depends_on = None


def ident(): return sa.Column("id", sa.Uuid(), nullable=False)
def timestamps(): return [sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)]
def jsonb(name: str, *, nullable: bool = False, default: str | None = None): return sa.Column(name, postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text(default) if default else None, nullable=nullable)


def upgrade() -> None:
    op.create_table("inventory_categories", sa.Column("key", sa.String(32), primary_key=True), sa.Column("display_name", sa.String(64), nullable=False), sa.Column("position", sa.Integer(), nullable=False), sa.Column("active", sa.Boolean(), server_default="true", nullable=False), *timestamps())
    op.bulk_insert(sa.table("inventory_categories", sa.column("key", sa.String), sa.column("display_name", sa.String), sa.column("position", sa.Integer), sa.column("active", sa.Boolean)), [
        {"key": "wardrobe", "display_name": "Wardrobe", "position": 1, "active": True}, {"key": "shoes", "display_name": "Shoes", "position": 2, "active": True},
        {"key": "accessories", "display_name": "Accessories", "position": 3, "active": True}, {"key": "beauty", "display_name": "Beauty", "position": 4, "active": True},
        {"key": "hair", "display_name": "Hair", "position": 5, "active": True}, {"key": "perfumes", "display_name": "Perfumes", "position": 6, "active": True},
        {"key": "supplements", "display_name": "Supplements", "position": 7, "active": True},
    ])
    op.create_table("inventory_items", ident(), sa.Column("account_id", sa.Uuid(), nullable=False), sa.Column("category", sa.String(32), nullable=False), sa.Column("subcategory", sa.String(80)), sa.Column("display_name", sa.String(160), nullable=False), sa.Column("brand", sa.String(120)), sa.Column("source", sa.String(32), server_default="user_declared", nullable=False), sa.Column("verification_state", sa.String(24), server_default="confirmed", nullable=False), sa.Column("confidence", sa.Float(), server_default="1", nullable=False), sa.Column("status", sa.String(24), server_default="active", nullable=False), sa.Column("purchase_date", sa.Date()), sa.Column("purchase_price", sa.Numeric(12, 2)), sa.Column("currency", sa.String(3), server_default="INR", nullable=False), sa.Column("usage_count", sa.Integer(), server_default="0", nullable=False), sa.Column("last_used_at", sa.Date()), sa.Column("condition", sa.String(24), server_default="good", nullable=False), sa.Column("replacement_priority", sa.String(24), server_default="none", nullable=False), sa.Column("version", sa.Integer(), server_default="1", nullable=False), sa.Column("client_mutation_id", sa.String(80)), sa.Column("source_ai_run_id", sa.Uuid()), sa.Column("model_version", sa.String(64)), sa.Column("prompt_version", sa.String(32)), sa.Column("schema_version", sa.String(32)), *timestamps(), sa.ForeignKeyConstraint(["account_id"], ["account_links.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["category"], ["inventory_categories.key"]), sa.ForeignKeyConstraint(["source_ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("account_id", "client_mutation_id", name="uq_inventory_client_mutation"))
    op.create_index("ix_inventory_items_account_category_status", "inventory_items", ["account_id", "category", "status"]); op.create_index("ix_inventory_items_account_updated", "inventory_items", ["account_id", "updated_at"]); op.create_index("ix_inventory_items_account_brand", "inventory_items", ["account_id", "brand"])
    op.create_table("inventory_item_images", ident(), sa.Column("item_id", sa.Uuid(), nullable=False), sa.Column("media_asset_id", sa.Uuid(), nullable=False), sa.Column("position", sa.Integer(), server_default="0", nullable=False), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["media_asset_id"], ["media_assets.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("item_id", "media_asset_id", name="uq_inventory_item_image")); op.create_index("ix_inventory_item_images_item", "inventory_item_images", ["item_id", "position"])
    op.create_table("inventory_attributes", ident(), sa.Column("item_id", sa.Uuid(), nullable=False), sa.Column("key", sa.String(64), nullable=False), jsonb("value"), sa.Column("source", sa.String(32), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("verification_state", sa.String(24), nullable=False), sa.Column("source_ai_run_id", sa.Uuid()), sa.Column("model_version", sa.String(64)), sa.Column("prompt_version", sa.String(32)), sa.Column("schema_version", sa.String(32)), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["source_ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("item_id", "key", name="uq_inventory_attribute_key")); op.create_index("ix_inventory_attributes_key_state", "inventory_attributes", ["key", "verification_state"])

    op.create_table("wardrobe_item_details", ident(), sa.Column("item_id", sa.Uuid(), nullable=False, unique=True), sa.Column("colour", sa.String(80)), sa.Column("pattern", sa.String(80)), sa.Column("fabric", sa.String(100)), sa.Column("fit", sa.String(80)), sa.Column("size", sa.String(40)), jsonb("season", default="'[]'::jsonb"), jsonb("occasion", default="'[]'::jsonb"), sa.Column("formality", sa.String(80)), sa.Column("laundry_state", sa.String(40)), sa.Column("care_instructions", sa.Text()), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("shoe_item_details", ident(), sa.Column("item_id", sa.Uuid(), nullable=False, unique=True), sa.Column("shoe_type", sa.String(80)), sa.Column("colour", sa.String(80)), sa.Column("size", sa.String(40)), sa.Column("heel_height", sa.Numeric(5, 1)), sa.Column("comfort", sa.String(80)), jsonb("occasion", default="'[]'::jsonb"), jsonb("weather_suitability", default="'[]'::jsonb"), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("accessory_item_details", ident(), sa.Column("item_id", sa.Uuid(), nullable=False, unique=True), sa.Column("accessory_type", sa.String(80)), sa.Column("colour", sa.String(80)), sa.Column("metal", sa.String(80)), sa.Column("material", sa.String(100)), sa.Column("style", sa.String(100)), jsonb("occasion", default="'[]'::jsonb"), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    for table in ("beauty_product_details", "hair_product_details"):
        op.create_table(table, ident(), sa.Column("item_id", sa.Uuid(), nullable=False, unique=True), sa.Column("product_type", sa.String(80)), sa.Column("size", sa.String(40)), sa.Column("opened_date", sa.Date()), sa.Column("expiry_date", sa.Date()), sa.Column("period_after_opening_months", sa.Integer()), sa.Column("purpose", sa.String(200)), sa.Column("ingredients_text", sa.Text()), jsonb("active_ingredients", default="'[]'::jsonb"), sa.Column("use_frequency", sa.String(80)), sa.Column("routine_position", sa.String(80)), sa.Column("remaining_percent", sa.Integer()), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("perfume_details", ident(), sa.Column("item_id", sa.Uuid(), nullable=False, unique=True), sa.Column("fragrance_family", sa.String(100)), sa.Column("concentration", sa.String(80)), jsonb("season", default="'[]'::jsonb"), jsonb("occasion", default="'[]'::jsonb"), sa.Column("longevity_user_reported", sa.String(100)), sa.Column("usage_frequency", sa.String(80)), sa.Column("remaining_percent", sa.Integer()), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("supplement_details", ident(), sa.Column("item_id", sa.Uuid(), nullable=False, unique=True), sa.Column("supplement_name", sa.String(160)), sa.Column("brand", sa.String(120)), sa.Column("user_entered_purpose", sa.String(240)), sa.Column("expiry_date", sa.Date()), sa.Column("opened_date", sa.Date()), sa.Column("use_frequency", sa.String(80)), sa.Column("label_information", sa.Text()), sa.Column("safety_disclaimer", sa.Text(), nullable=False), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))

    op.create_table("item_usage_events", ident(), sa.Column("item_id", sa.Uuid(), nullable=False), sa.Column("used_on", sa.Date(), nullable=False), sa.Column("quantity", sa.Integer(), server_default="1", nullable=False), sa.Column("note", sa.String(240)), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id")); op.create_index("ix_item_usage_events_item_date", "item_usage_events", ["item_id", "used_on"])
    op.create_table("item_condition_events", ident(), sa.Column("item_id", sa.Uuid(), nullable=False), sa.Column("condition", sa.String(24), nullable=False), sa.Column("note", sa.String(240)), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("item_expiry_events", ident(), sa.Column("item_id", sa.Uuid(), nullable=False), sa.Column("expiry_date", sa.Date(), nullable=False), sa.Column("source", sa.String(32), nullable=False), sa.Column("note", sa.String(240)), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("item_relationships", ident(), sa.Column("account_id", sa.Uuid(), nullable=False), sa.Column("from_item_id", sa.Uuid(), nullable=False), sa.Column("to_item_id", sa.Uuid(), nullable=False), sa.Column("relationship_type", sa.String(40), nullable=False), *timestamps(), sa.ForeignKeyConstraint(["account_id"], ["account_links.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["from_item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["to_item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("duplicate_candidates", ident(), sa.Column("account_id", sa.Uuid(), nullable=False), sa.Column("item_a_id", sa.Uuid(), nullable=False), sa.Column("item_b_id", sa.Uuid(), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("reason", sa.String(240), nullable=False), sa.Column("status", sa.String(24), server_default="pending", nullable=False), sa.Column("resolution", sa.String(32)), sa.Column("resolved_at", sa.DateTime(timezone=True)), *timestamps(), sa.ForeignKeyConstraint(["account_id"], ["account_links.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["item_a_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["item_b_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("account_id", "item_a_id", "item_b_id", name="uq_duplicate_candidate_pair")); op.create_index("ix_duplicate_candidates_account_status", "duplicate_candidates", ["account_id", "status"])
    op.create_table("inventory_import_jobs", ident(), sa.Column("account_id", sa.Uuid(), nullable=False), sa.Column("capture_type", sa.String(32), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("media_asset_id", sa.Uuid()), sa.Column("ai_run_id", sa.Uuid()), sa.Column("detected_count", sa.Integer(), server_default="0", nullable=False), sa.Column("error_code", sa.String(64)), sa.Column("completed_at", sa.DateTime(timezone=True)), *timestamps(), sa.ForeignKeyConstraint(["account_id"], ["account_links.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["media_asset_id"], ["media_assets.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_value_events", ident(), sa.Column("item_id", sa.Uuid(), nullable=False), sa.Column("metric_version", sa.String(16), nullable=False), sa.Column("estimated_value", sa.Numeric(12, 2)), sa.Column("currency", sa.String(3), nullable=False), jsonb("inputs"), sa.Column("explanation", sa.Text(), nullable=False), *timestamps(), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_events", ident(), sa.Column("account_id", sa.Uuid(), nullable=False), sa.Column("item_id", sa.Uuid()), sa.Column("event_type", sa.String(48), nullable=False), sa.Column("actor", sa.String(32), nullable=False), jsonb("payload", default="'{}'::jsonb"), *timestamps(), sa.ForeignKeyConstraint(["account_id"], ["account_links.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id")); op.create_index("ix_inventory_events_account_item", "inventory_events", ["account_id", "item_id", "created_at"])


def downgrade() -> None:
    for table in ["inventory_events", "inventory_value_events", "inventory_import_jobs", "duplicate_candidates", "item_relationships", "item_expiry_events", "item_condition_events", "item_usage_events", "supplement_details", "perfume_details", "hair_product_details", "beauty_product_details", "accessory_item_details", "shoe_item_details", "wardrobe_item_details", "inventory_attributes", "inventory_item_images", "inventory_items", "inventory_categories"]:
        op.drop_table(table)
