"""add system worker status

Revision ID: 18402a5773ce
Revises: 0001
Create Date: 2026-08-05 20:54:05.418736
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18402a5773ce'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_worker_status',
    sa.Column('worker_name', sa.String(length=100), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_name')
    )
    op.create_index('idx_worker_status_name', 'system_worker_status', ['worker_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_worker_status_name', table_name='system_worker_status')
    op.drop_table('system_worker_status')
    # ### end Alembic commands ###
