"""add system worker status

Revision ID: 18402a5773ce
Revises: 0005_shopping_idempotency
Create Date: 2026-08-05 19:42:39.947453
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18402a5773ce'
down_revision: Union[str, None] = '0005_shopping_idempotency'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
