"""Add air_quality_snapshots and system_worker_status

Revision ID: ee2713cab5de
Revises: 0001
Create Date: 2026-08-08 06:52:53.993770
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

"""Add air_quality_snapshots and system_worker_status

Revision ID: ee2713cab5de
Revises: 0001
Create Date: 2026-08-08 06:52:53.993770
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ee2713cab5de'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality_snapshots',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=False),
    sa.Column('index_system', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('prominent_pollutant', sa.String(length=32), nullable=True),
    sa.Column('pm2_5', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), server_default='manual', nullable=False),
    sa.Column('source', sa.String(length=32), server_default='user_declared', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_air_quality_snapshots_account_date', 'air_quality_snapshots', ['account_id', 'for_date', 'created_at'], unique=False)
    
    # We retain the DailyPlan FK as it is actively used to preserve the same 
    # auditable snapshot relationship that weather already has.
    op.add_column('daily_plans', sa.Column('air_quality_snapshot_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_daily_plans_aqi_snapshot', 'daily_plans', 'air_quality_snapshots', ['air_quality_snapshot_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('weather_snapshots', sa.Column('uv_index', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_daily_plans_aqi_snapshot', 'daily_plans', type_='foreignkey')
    op.drop_column('daily_plans', 'air_quality_snapshot_id')
    op.drop_index('ix_air_quality_snapshots_account_date', table_name='air_quality_snapshots')
    op.drop_table('air_quality_snapshots')
    op.drop_column('weather_snapshots', 'uv_index')
    # ### end Alembic commands ###
