"""Supplement absorption knowledge base (extends VC-07).

Release-owned reference data keyed on canonical_component_key. Additive: it
creates one new table and touches nothing existing.

Original autogenerate header

Revision ID: 9ddc5dd1f429
Revises: m3n4o5p6q7
Create Date: 2026-08-30 12:36:08.660246
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "n4o5p6q7r8"
down_revision: Union[str, None] = "m3n4o5p6q7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplement_component_knowledge',
    sa.Column('canonical_component_key', sa.String(length=160), nullable=False),
    sa.Column('nutrient', sa.String(length=120), nullable=False),
    sa.Column('compound_form', sa.String(length=160), nullable=False),
    sa.Column('elemental_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('percent_kind', sa.String(length=32), nullable=True),
    sa.Column('hydration_note', sa.Text(), nullable=True),
    sa.Column('absorption_summary', sa.Text(), nullable=True),
    sa.Column('absorption_value', sa.String(length=256), nullable=True),
    sa.Column('absorption_unit', sa.String(length=64), nullable=True),
    sa.Column('disagreement', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_identifier', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('evidence_tier', sa.String(length=32), nullable=False),
    sa.Column('verification', sa.String(length=16), server_default='unverified', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_claim_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("absorption_value IS NULL OR (source_url IS NOT NULL AND btrim(source_url) <> '')", name='ck_supplement_knowledge_absorption_needs_source'),
    sa.CheckConstraint("confidence IS NULL OR confidence IN ('high', 'medium', 'low')", name='ck_supplement_knowledge_confidence'),
    sa.CheckConstraint("verification IN ('unverified', 'confirmed', 'disputed')", name='ck_supplement_knowledge_verification'),
    sa.CheckConstraint('absorption_value IS NULL OR confidence IS NOT NULL', name='ck_supplement_knowledge_absorption_needs_confidence'),
    sa.CheckConstraint('elemental_percent IS NULL OR (elemental_percent > 0 AND elemental_percent <= 100)', name='ck_supplement_knowledge_percent_range'),
    sa.ForeignKeyConstraint(['evidence_claim_id'], ['evidence_claims.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_component_key', 'compound_form', name='uq_supplement_knowledge_form')
    )
    op.create_index('ix_supplement_knowledge_key', 'supplement_component_knowledge', ['canonical_component_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplement_knowledge_key', table_name='supplement_component_knowledge')
    op.drop_table('supplement_component_knowledge')
    # ### end Alembic commands ###
