"""Barcode scanning: anonymous devices, product records, scan events.

Additive. Store B only — Open Food Facts data lives in its own schema and is
not touched here.

Original autogenerate header

Revision ID: 61721eb79e95
Revises: n4o5p6q7r8
Create Date: 2026-08-30 14:47:31.039650
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "o5p6q7r8s9"
down_revision: Union[str, None] = "n4o5p6q7r8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_records',
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.String(length=32), server_default='not_enough_information', nullable=False),
    sa.Column('fssai_licence', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=24), server_default='off', nullable=False),
    sa.Column('confirmation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('verified', 'community', 'unverified', 'not_enough_information')", name='ck_product_records_confidence'),
    sa.CheckConstraint('confirmation_count >= 0', name='ck_product_records_confirmations'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index('ix_product_records_confidence', 'product_records', ['confidence'], unique=False)
    op.create_table('scan_devices',
    sa.Column('device_key', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=24), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('claimed_by_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_key')
    )
    op.create_index('ix_scan_devices_claimed', 'scan_devices', ['claimed_by_account_id'], unique=False)
    op.create_table('scan_events',
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('client_scan_id', sa.String(length=64), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_offline', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('label_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['scan_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'client_scan_id', name='uq_scan_event_device_client_id')
    )
    op.create_index('ix_scan_events_barcode', 'scan_events', ['barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_events_barcode', table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index('ix_scan_devices_claimed', table_name='scan_devices')
    op.drop_table('scan_devices')
    op.drop_index('ix_product_records_confidence', table_name='product_records')
    op.drop_table('product_records')
    # ### end Alembic commands ###
