"""Multi-item capture: shelf-photo candidates awaiting one tap.

A candidate is not an inventory item. Fifteen guesses from one photo must not
reach the shelf, a routine or the duplicates queue before a person has looked
at them, so they wait here until one tap accepts or rejects each.

Revision ID: p6q7r8s9t0
Revises: o5p6q7r8s9
Create Date: 2026-08-30 16:52:46.173042
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'p6q7r8s9t0'
down_revision: Union[str, None] = 'o5p6q7r8s9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_import_candidates',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subcategory', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('uncertain_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('photo_quality_notes', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'confirmed', 'rejected')", name='ck_import_candidate_state'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_import_candidate_confidence'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['inventory_import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_candidates_account_state', 'inventory_import_candidates', ['account_id', 'state'], unique=False)
    op.create_index('ix_import_candidates_job', 'inventory_import_candidates', ['job_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_candidates_job', table_name='inventory_import_candidates')
    op.drop_index('ix_import_candidates_account_state', table_name='inventory_import_candidates')
    op.drop_table('inventory_import_candidates')
    # ### end Alembic commands ###
