"""Somebody told us a number on a pack is wrong.

Error reports get their own table rather than riding on scan_events: a
complaint is not a scan, and filing it as one would put it in the person's scan
history and count towards how much they have scanned.

Revision ID: r8s9t0u1v2
Revises: q7r8s9t0u1
Create Date: 2026-08-30 18:36:02.116884
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'r8s9t0u1v2'
down_revision: Union[str, None] = 'q7r8s9t0u1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_error_reports',
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('client_report_id', sa.String(length=64), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_key', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['scan_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'client_report_id', name='uq_label_report_device_client_id')
    )
    op.create_index('ix_label_error_reports_barcode', 'label_error_reports', ['barcode', 'created_at'], unique=False)
    op.create_index('ix_label_error_reports_open', 'label_error_reports', ['resolved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_label_error_reports_open', table_name='label_error_reports')
    op.drop_index('ix_label_error_reports_barcode', table_name='label_error_reports')
    op.drop_table('label_error_reports')
    # ### end Alembic commands ###
